"""add_simple_learning_events

Revision ID: 4374b8842427
Revises: fee3346a2bfe
Create Date: 2025-12-17 19:15:42.819398

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = "4374b8842427"
down_revision: str | None = "fee3346a2bfe"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
