"""Add recommendations tables

Revision ID: 83c6f7c7c0b9
Revises: 4f8a9c2b5d3e
Create Date: 2025-12-17 18:00:08.597279

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '83c6f7c7c0b9'
down_revision: str | None = '4f8a9c2b5d3e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_activity_sessions_student'), table_name='activity_sessions')
    op.drop_index(op.f('idx_learning_events_session'), table_name='learning_events')
    op.drop_index(op.f('idx_learning_events_student'), table_name='learning_events')
    op.drop_index(op.f('idx_mastery_states_student'), table_name='mastery_states')
    op.drop_index(op.f('idx_metric_aggregates_student'), table_name='metric_aggregates')
    op.drop_index(op.f('idx_microconcepts_subject'), table_name='microconcepts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_microconcepts_subject'), 'microconcepts', ['subject_id'], unique=False)
    op.create_index(op.f('idx_metric_aggregates_student'), 'metric_aggregates', ['student_id'], unique=False)
    op.create_index(op.f('idx_mastery_states_student'), 'mastery_states', ['student_id'], unique=False)
    op.create_index(op.f('idx_learning_events_student'), 'learning_events', ['student_id'], unique=False)
    op.create_index(op.f('idx_learning_events_session'), 'learning_events', ['session_id'], unique=False)
    op.create_index(op.f('idx_activity_sessions_student'), 'activity_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###
