"""Add recommendations tables V2

Revision ID: fee3346a2bfe
Revises: 83c6f7c7c0b9
Create Date: 2025-12-17 18:09:03.930037

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = "fee3346a2bfe"
down_revision: str | None = "83c6f7c7c0b9"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_instances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("microconcept_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="recommendation_priority"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="recommendation_status"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["microconcept_id"],
            ["microconcepts.id"],
            name="recommendation_instances_microconcept_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name="recommendation_instances_student_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recommendation_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendation_instances.id"],
            name="recommendation_evidence_recommendation_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tutor_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("tutor_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("decision_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendation_instances.id"],
            name="tutor_decisions_recommendation_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tutor_id"], ["tutors.id"], name="tutor_decisions_tutor_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recommendation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tutor_decisions")
    op.drop_table("recommendation_evidence")
    op.drop_table("recommendation_instances")
    # ### end Alembic commands ###
